# Generated by Django 3.1.7 on 2021-04-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('invitations', '0003_auto_20151126_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=64)),
                ('refresh_token', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationMeta',
            fields=[
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invitations.invitation')),
                ('employee_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('role', models.CharField(choices=[('mgr', 'Manager'), ('emp', 'Employee')], default='emp', max_length=8)),
                ('employee_id', models.CharField(blank=True, default='', max_length=8)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timecardsite.account')),
            ],
        ),
    ]
